# Ranked PvP Battleground configuration
gameserver.rankedbg.enable=true
gameserver.rankedbg.mapid=300350000
gameserver.rankedbg.max.team.size=6
gameserver.rankedbg.tick.seconds=5
gameserver.rankedbg.match.minutes=10
gameserver.rankedbg.prep.seconds=60
gameserver.rankedbg.kill.points=100
gameserver.rankedbg.win.points=3
gameserver.rankedbg.match.rating.tolerance=300
gameserver.rankedbg.elo.k=32
gameserver.rankedbg.ap.win=1500
gameserver.rankedbg.ap.lose=300
gameserver.rankedbg.season.win=10
gameserver.rankedbg.season.lose=3
gameserver.rankedbg.default.rating=1000
